In [3]:
import numpy as np
import pandas as pd

%matplotlib inline

## **Задание на повторение материала

In [27]:
#1. Создать одномерный массив Numpy под названием a из 12 последовательных 
# целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [34]:
#2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

#Сразу сделал универсальный метод
b = [a.reshape(i,len(a)//i) for i in range(2,len(a) + 1) if len(a) % i == 0]
b

[array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]), array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]])]

In [41]:
#3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
# (в трех примерах - для обозначения числа столбцов, в двух - для строк).

c1 = [a.reshape(i,-1) for i in range(2,len(a) + 1) if len(a) % i == 0][:3]
print(c1)

c2 = [a.reshape(-1,i) for i in range(2,len(a) + 1) if len(a) % i == 0][:2]
c2

[array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]]), array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])]


[array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]), array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])]

In [62]:
#4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

# Для примера берем последний элемент списка из пункта 2 - там уже был вертикальный вектор. 
# Сделал "вручную", без flatten
d = b[-1]
d = d.T[0]
d

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [68]:
#5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой 
# из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
e = np.random.randn(3,4)
print(e)

f = e.flatten()
f

[[ 0.86928951 -0.67938227  2.01573012  0.7779563 ]
 [ 0.2253445   2.20482027  0.3818926   0.90586465]
 [-0.21950103  0.22417243 -1.15659216 -0.15392866]]


array([ 0.86928951, -0.67938227,  2.01573012,  0.7779563 ,  0.2253445 ,
        2.20482027,  0.3818926 ,  0.90586465, -0.21950103,  0.22417243,
       -1.15659216, -0.15392866])

In [69]:
#6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [91]:
#7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно 
# с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20,1, -2)
b.resize(1, len(b))
b

#ОТВЕТ - разница в то что a - одмерная структура, b - двумерная

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [90]:
#8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
# число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 
# Итоговый массив v должен иметь атрибут size, равный 10.

a = np.zeros([2,2])
print(a)

b = np.ones([3,2])
print(b)
v = np.vstack([a, b])
print(v)
v.size


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [99]:
#9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
# состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12).reshape(4,3)
print(a)
At = a.T
print(At)
B = np.dot(a, At)
print(B)
#Размер B
print(f'Shape of B:{B.shape}, size: {B.size}')

Bdet = np.linalg.det(B)
Bdet

# Детерминант = 0, поэтому обратной матрицы не существует

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Shape of B:(4, 4), size: 16


0.0

In [112]:
#10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(10)

In [113]:
#11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно 
# распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([ 9, 13,  4, 15,  0,  1, 11, 12,  9, 13,  0, 13,  1, 10,  8,  9])

In [128]:
#12. Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
import math
print(B)
C = c.reshape(int(math.sqrt(len(c))), int(math.sqrt(len(c))))
print(C)
D= B + C * 10
print(D)

D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print('Matrix D: Det {}, Rank {}, Inv {}'.format(D_det, D_rank, D_inv))

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 9 13  4 15]
 [ 0  1 11 12]
 [ 9 13  0 13]
 [ 1 10  8  9]]
[[ 95 144  63 182]
 [ 14  60 196 242]
 [113 216 149 342]
 [ 42 222 292 392]]
Matrix D: Det 70010399.99999993, Rank 4, Inv [[ 0.04365894  0.01516746 -0.02770303 -0.00546433]
 [-0.00033624 -0.01367968 -0.00180459  0.01017563]
 [ 0.03145161  0.00806452 -0.02983871  0.00645161]
 [-0.02791557  0.00011484  0.02621696 -0.00743204]]


In [142]:
#13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 

D_inv2 = D_inv.copy()
D_inv2[(D_inv2 < 0)] = 0
D_inv2[(D_inv2 > 0)] = 1
D_inv2

array([[1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.]])

In [141]:
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
#   а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
#   должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
#   для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

E = np.where(D_inv2 > 0, B, C)
E

array([[  5,  14,   4,  15],
       [  0,   1,  11, 122],
       [ 23,  86,   0, 212],
       [  1, 122, 212,   9]])